import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {LayoutDashboard, BriefcaseBusiness, WalletCards, CreditCard, Landmark, Receipt, ShieldCheck, Target, Lightbulb, Bell, Settings, Plus, Search, Moon, Sun, Download, Upload, Trash2, TrendingUp, Menu, X, CalendarDays, Repeat2, PiggyBank, CircleDollarSign, RefreshCw} from 'lucide-react';
import './styles.css';
import { fetchAmfiNavs, fetchStockLtp, calcHolding, connectStockStream, normalizeStockQuoteMap } from './market.js';

const base={version:3,settings:{theme:'light',currency:'INR'},income:[],expenses:[],recurring:[],assets:[],cards:[],debts:[],insurance:[],goals:[],reminders:[],snapshots:[],investmentTransactions:[]};
const nav=[['Dashboard',LayoutDashboard],['Holdings',BriefcaseBusiness],['Assets',WalletCards],['Credit Cards',CreditCard],['Debts / Loans',Landmark],['Expenses',Receipt],['Insurance',ShieldCheck],['Goals',Target],['Insights',Lightbulb],['Reminders',Bell],['Settings',Settings]];
const assetTypes=['Savings','Cash','FD','RD','Equity','Mutual Fund','Gold','PPF','NPS','Crypto','Other'];
const expenseCats=['Food','Travel','Shopping','Bills','Rent/PG','Entertainment','Health','Education','Subscriptions','Family','Other'];
const incomeCats=['Salary','Dividend','Interest','Bonus','Freelance','Other'];
const frequency=['Daily','Weekly','Monthly','Yearly'];
const id=()=>crypto?.randomUUID?.()||String(Date.now()+Math.random());
const money=n=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Number(n)||0);
const pct=n=>`${Number(n||0).toFixed(2)}%`;
const today=()=>new Date().toISOString().slice(0,10);
function safeLoad(){try{const raw=JSON.parse(localStorage.getItem('my-wealth-data')||'null');return raw?{...base,...raw}:base}catch{return base}}
const DB_NAME='my-wealth-db', DB_STORE='app';
function openDB(){return new Promise((resolve,reject)=>{if(!('indexedDB' in window))return reject(new Error('IndexedDB unavailable'));const r=indexedDB.open(DB_NAME,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(DB_STORE))r.result.createObjectStore(DB_STORE)};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function dbGet(){const db=await openDB();return new Promise((resolve,reject)=>{const r=db.transaction(DB_STORE,'readonly').objectStore(DB_STORE).get('state');r.onsuccess=()=>resolve(r.result||null);r.onerror=()=>reject(r.error)})}
async function dbPut(value){const db=await openDB();return new Promise((resolve,reject)=>{const r=db.transaction(DB_STORE,'readwrite').objectStore(DB_STORE).put(value,'state');r.onsuccess=()=>resolve();r.onerror=()=>reject(r.error)})}
function useStore(){const [data,setData]=useState(base);const [ready,setReady]=useState(false);useEffect(()=>{let alive=true;(async()=>{try{const stored=await dbGet();if(alive)setData(stored?{...base,...stored}:safeLoad())}catch{if(alive)setData(safeLoad())}finally{if(alive)setReady(true)}})();return()=>{alive=false}},[]);useEffect(()=>{if(!ready)return;dbPut(data).catch(()=>localStorage.setItem('my-wealth-data',JSON.stringify(data)))},[data,ready]);return[data,setData,ready]}
function Card({children,className=''}){return <section className={'card '+className}>{children}</section>}
function Stat({label,value,sub,positive}){return <div className="stat"><div className="eyebrow">{label}</div><div className="statValue">{value}</div>{sub&&<div className={positive===true?'positive':positive===false?'negative':'muted'}>{sub}</div>}</div>}
function Button({children,onClick,secondary=false,danger=false}){return <button className={danger?'dangerBtn':secondary?'secondary':'primary'} onClick={onClick}>{children}</button>}
function Modal({title,onClose,children}){return <div className="modalBack"><div className="modal"><div className="modalHead"><h3>{title}</h3><button className="iconBtn" onClick={onClose}><X size={17}/></button></div>{children}</div></div>}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
function Dashboard({data,setPage}){
 const assets=data.assets; const totalAssets=assets.reduce((s,a)=>s+Number(a.value||0),0); const debt=data.debts.reduce((s,a)=>s+Number(a.outstanding||0),0); const cardDebt=data.cards.reduce((s,a)=>s+Number(a.outstanding||0),0); const net=totalAssets-debt-cardDebt;
 const invested=assets.filter(a=>['Equity','Mutual Fund','Gold'].includes(a.type)).reduce((s,a)=>s+Number(a.value||0),0); const cost=assets.filter(a=>['Equity','Mutual Fund','Gold'].includes(a.type)).reduce((s,a)=>s+Number(a.invested||a.value||0),0); const ret=cost?(invested-cost)/cost*100:0;
 const month=new Date().toISOString().slice(0,7); const inc=data.income.filter(x=>String(x.date).startsWith(month)).reduce((s,x)=>s+Number(x.amount||0),0); const exp=data.expenses.filter(x=>String(x.date).startsWith(month)).reduce((s,x)=>s+Number(x.amount||0),0); const savings=inc?((inc-exp)/inc*100):0;
 const groups={};assets.forEach(a=>groups[a.type]=(groups[a.type]||0)+Number(a.value||0));
 return <div className="dash"><Card className="hero"><div className="eyebrow">TOTAL NET WORTH</div><div className="heroMoney">{money(net)}</div><div className="positive">Assets {money(totalAssets)} · Liabilities {money(debt+cardDebt)}</div></Card>
 <div className="statsGrid"><Stat label="Net worth returns" value={pct(ret)} sub="Current tracked investments" positive={ret>=0}/><Stat label="Since inception" value={pct(ret)} sub="Based on invested cost" positive={ret>=0}/><Stat label="Net cashflow" value={money(inc-exp)} sub={`${money(inc)} income − ${money(exp)} expense`} positive={inc-exp>=0}/><Stat label="Savings rate" value={pct(savings)} sub="This month" positive={savings>=0}/><Stat label="Debt health" value={debt+cardDebt?money(debt+cardDebt):'Debt-free'} sub={debt+cardDebt?'Outstanding liabilities':'No tracked debt'} positive={!debt&&!cardDebt}/><Stat label="Next 30 days" value={money(data.reminders.reduce((s,r)=>s+Number(r.amount||0),0))} sub="Tracked commitments"/></div>
 <div className="grid3"><Card><Head n="01" title="Asset Allocation" action="Assets" onClick={()=>setPage('Assets')}/><Allocation groups={groups}/></Card><Card><Head n="02" title="Top Holdings" action="Holdings" onClick={()=>setPage('Holdings')}/><Holdings assets={assets}/></Card><Card><Head n="03" title="Portfolio Overview" action="Insights" onClick={()=>setPage('Insights')}/><div className="drift">{[['Equity','60'],['Mutual Fund','20'],['Gold','10'],['Cash','10']].map(([t,target])=>{let actual=totalAssets?(assets.filter(a=>a.type===t||t==='Cash'&&['Savings','Cash'].includes(a.type)).reduce((s,a)=>s+a.value,0)/totalAssets*100):0;return <div className="driftRow" key={t}><div><b>{t}</b><small>{actual.toFixed(1)}% actual · {target}% target</small></div><span className={actual>Number(target)?'bad':'good'}>{actual>Number(target)?'+':''}{(actual-Number(target)).toFixed(1)}%</span></div>})}</div></Card></div>
 <div className="grid2"><Card><Head n="04" title="Upcoming & Commitments" action="Reminders" onClick={()=>setPage('Reminders')}/>{data.recurring.length?data.recurring.slice(0,4).map(r=><div className="lineRow" key={r.id}><div><b>{r.name}</b><small>{r.frequency} · {r.category}</small></div><strong>{money(r.amount)}</strong></div>):<Empty icon={<CalendarDays/>} title="You're all set" text="Add recurring bills, SIPs or reminders."/>}</Card><Card><Head n="05" title="Expenses" action="Expenses" onClick={()=>setPage('Expenses')}/><div className="expenseTiles"><div><span>THIS MONTH</span><b>{money(exp)}</b></div><div><span>TRANSACTIONS</span><b>{data.expenses.filter(x=>String(x.date).startsWith(month)).length}</b></div></div><div className="quickActions"><Button onClick={()=>setPage('Expenses')}><Plus size={16}/> Add expense</Button><Button secondary onClick={()=>setPage('Insights')}><TrendingUp size={16}/> View insights</Button></div></Card></div>
 </div>
}
function Head({n,title,action,onClick}){return <div className="cardHead"><h2><span>{n}</span>{title}</h2>{action&&<button className="link" onClick={onClick}>{action} →</button>}</div>}
function Empty({icon,title,text}){return <div className="emptyState">{icon}<b>{title}</b><span>{text}</span></div>}
function Allocation({groups}){const entries=Object.entries(groups),total=entries.reduce((s,[,v])=>s+v,0)||1;return <div className="allocation"><div className="donut" style={{'--a':`${(groups['Equity']||0)/total*360}deg`}}><div/></div><div className="legend">{entries.slice(0,6).map(([k,v],i)=><span key={k}><i className={'c'+i}/>{k} {pct(v/total*100)}</span>)}</div></div>}
function Holdings({assets}){const list=assets.filter(a=>['Equity','Mutual Fund','Gold'].includes(a.type)).sort((a,b)=>b.value-a.value).slice(0,7);return <div className="holdings">{list.length?list.map(a=>{const pl=Number(a.value||0)-Number(a.invested||a.value||0);return <div className="holding" key={a.id}><div><b>{a.name}</b><small>{a.type}</small></div><strong>{money(a.value)}</strong><em className={pl>=0?'positive':'negative'}>{pl>=0?'+':'−'}{money(Math.abs(pl))}</em></div>}):<Empty title="No holdings" text="Add equity, mutual fund or gold assets."/>}</div>}
function Layout({page,setPage,data,setData,dark,setDark}){const [menu,setMenu]=useState(false);return <div className="app"><aside className={menu?'sidebar open':'sidebar'}><div className="brand">My <span>Wealth</span></div><div className="nav">{nav.map(([name,Icon])=><button key={name} className={page===name?'navItem active':'navItem'} onClick={()=>{setPage(name);setMenu(false)}}><Icon size={18}/><span>{name}</span></button>)}</div><div className="sidebarBottom"><button className="navItem" onClick={()=>setDark(!dark)}>{dark?<Sun size={18}/>:<Moon size={18}/>}<span>{dark?'Light mode':'Dark mode'}</span></button></div></aside>{menu&&<div className="overlay" onClick={()=>setMenu(false)}/>}<main><header><button className="mobileMenu" onClick={()=>setMenu(true)}><Menu/></button><div><h1>{page}</h1><div className="date">{new Date().toLocaleDateString('en-IN',{weekday:'long',day:'2-digit',month:'long',year:'numeric'})}</div></div><button className="iconBtn" onClick={()=>setPage('Reminders')}><BellIcon/></button></header><div className="content"><Page page={page} data={data} setData={setData} setPage={setPage}/></div></main></div>}
function BellIcon(){return <Bell size={18}/>}
function Page({page,data,setData,setPage}){if(page==='Dashboard')return <Dashboard data={data} setPage={setPage}/>;if(page==='Holdings')return <HoldingsPage data={data} setData={setData}/>;if(page==='Assets')return <Assets data={data} setData={setData}/>;if(page==='Expenses')return <Transactions type="expense" data={data} setData={setData}/>;if(page==='Credit Cards')return <Cards data={data} setData={setData}/>;if(page==='Debts / Loans')return <Debts data={data} setData={setData}/>;if(page==='Insurance')return <Insurance data={data} setData={setData}/>;if(page==='Goals')return <Goals data={data} setData={setData}/>;if(page==='Insights')return <Insights data={data}/>;if(page==='Reminders')return <Reminders data={data} setData={setData}/>;return <SettingsPage data={data} setData={setData}/>}
function PageTitle({title,text,children}){return <div className="pageIntro"><div><h2>{title}</h2><p>{text}</p></div>{children}</div>}
function fifoSell(lots, qty, sellPrice, fees=0){
  let remaining=Number(qty)||0, cost=0, newLots=[];
  for(const lot of (lots||[])){
    if(remaining<=0){newLots.push(lot);continue}
    const take=Math.min(remaining, Number(lot.units)||0);
    cost += take * Number(lot.price||0);
    const left=(Number(lot.units)||0)-take;
    if(left>1e-10)newLots.push({...lot,units:left});
    remaining-=take;
  }
  if(remaining>1e-8) throw new Error(`Not enough units. Short by ${remaining.toFixed(4)}.`);
  const proceeds=Number(qty)*Number(sellPrice)-Number(fees||0);
  return {lots:newLots, realizedPnl:proceeds-cost, costBasis:cost};
}
function xirr(cashflows){
  if(cashflows.length<2)return null;
  const dates=cashflows.map(x=>new Date(x.date).getTime()); const d0=dates[0];
  const f=r=>cashflows.reduce((s,x,i)=>s+x.amount/Math.pow(1+r,(dates[i]-d0)/31536000000),0);
  let r=.1;
  for(let i=0;i<80;i++){
    const h=1e-6, y=f(r), dy=(f(r+h)-f(r-h))/(2*h);
    if(!Number.isFinite(dy)||Math.abs(dy)<1e-12)break;
    const nr=r-y/dy;if(!Number.isFinite(nr)||nr<=-0.9999||nr>100)break;
    if(Math.abs(nr-r)<1e-8){r=nr;break} r=nr;
  }
  return Number.isFinite(r)?r*100:null;
}
function InvestmentTransactions({asset,data,setData,onClose}){
  const [f,setF]=useState({type:'BUY',date:today(),units:'',price:asset.price||'',fees:'',dividend:'',ratio:'1'});
  const [err,setErr]=useState('');
  const save=()=>{
    setErr('');
    try{
      const units=Number(f.units||0), price=Number(f.price||0), fees=Number(f.fees||0), ratio=Number(f.ratio||1);
      if(!f.date)throw Error('Choose a transaction date.');
      if(['BUY','SELL','SIP'].includes(f.type) && (!units||!price))throw Error('Units and price are required.');
      if(f.type==='DIVIDEND' && !Number(f.dividend))throw Error('Dividend amount is required.');
      setData(d=>{
        const assets=d.assets.map(a=>({...a})); const idx=assets.findIndex(a=>a.id===asset.id); if(idx<0)throw Error('Asset not found.');
        const a=assets[idx]; const txs=[...(d.investmentTransactions||[])];
        let tx={id:id(),assetId:a.id,type:f.type,date:f.date,units,price,fees,dividend:Number(f.dividend||0),ratio,createdAt:new Date().toISOString()};
        let lots=[...(a.lots||[])];
        if(f.type==='BUY'||f.type==='SIP'){
          lots.push({id:tx.id,date:f.date,units,price:price+(fees/units||0)});
          a.units=Number(a.units||0)+units; a.invested=Number(a.invested||0)+(units*price)+fees;
          a.price=price; a.value=Number(a.units)*price;
        } else if(f.type==='SELL'){
          const sold=fifoSell(lots,units,price,fees); lots=sold.lots; a.units=Math.max(0,Number(a.units||0)-units);
          const basis=sold.costBasis; a.invested=Math.max(0,Number(a.invested||0)-basis); a.value=Number(a.units)*price; tx.realizedPnl=sold.realizedPnl; tx.costBasis=basis;
        } else if(f.type==='DIVIDEND'){
          tx.units=0; a.value=Number(a.value||0); d.income=[...(d.income||[]),{id:id(),amount:Number(f.dividend),category:'Dividend',note:`${a.name} dividend`,date:f.date}];
        } else if(f.type==='FEE'){
          a.invested=Number(a.invested||0)+fees; tx.fee=fees;
        } else if(f.type==='SPLIT'||f.type==='BONUS'){
          if(ratio<=0)throw Error('Ratio must be greater than zero.');
          a.units=Number(a.units||0)*ratio; a.value=Number(a.units)*Number(a.price||price||0); tx.units=a.units;
        }
        a.lots=lots; a.updatedAt=new Date().toISOString(); assets[idx]=a; txs.unshift(tx);
        return {...d,assets,investmentTransactions:txs};
      });
      onClose();
    }catch(e){setErr(e.message||'Could not save transaction.');}
  };
  return <Modal title={`Add investment transaction · ${asset.name}`} onClose={onClose}>
    <div className="modalGrid"><Field label="Type"><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{['BUY','SELL','SIP','DIVIDEND','FEE','SPLIT','BONUS'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Date"><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/></Field>
    {['BUY','SELL','SIP'].includes(f.type)&&<><Field label="Units"><input type="number" step="any" value={f.units} onChange={e=>setF({...f,units:e.target.value})}/></Field><Field label="Price / NAV"><input type="number" step="any" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/></Field><Field label="Fees / charges"><input type="number" step="any" value={f.fees} onChange={e=>setF({...f,fees:e.target.value})}/></Field></>}
    {f.type==='DIVIDEND'&&<Field label="Dividend amount"><input type="number" step="any" value={f.dividend} onChange={e=>setF({...f,dividend:e.target.value})}/></Field>}
    {f.type==='FEE'&&<Field label="Fee amount"><input type="number" step="any" value={f.fees} onChange={e=>setF({...f,fees:e.target.value})}/></Field>}
    {['SPLIT','BONUS'].includes(f.type)&&<Field label="Ratio"><input type="number" step="any" value={f.ratio} onChange={e=>setF({...f,ratio:e.target.value})}/></Field>}
    </div>{err&&<div className="errorBox">{err}</div>}<div className="modalActions"><Button secondary onClick={onClose}>Cancel</Button><Button onClick={save}>Save transaction</Button></div>
  </Modal>
}
function MarketPortfolio({data,setData}){
  const market=data.settings.market||{};
  const holdings=data.assets.filter(a=>['Equity','Mutual Fund','Gold'].includes(a.type));
  const [quotes,setQuotes]=useState({}); const [status,setStatus]=useState({ok:false,message:'Configure market data in Settings.'}); const [busy,setBusy]=useState(false); const [last,setLast]=useState(null);
  const stockHoldings=holdings.filter(a=>a.type==='Equity'&&a.marketToken);
  const mfHoldings=holdings.filter(a=>a.type==='Mutual Fund'&&a.amfiIsin);
  const refresh=async()=>{
    if(!stockHoldings.length&&!mfHoldings.length){setStatus({ok:false,message:'Add a stock market token or mutual-fund ISIN to a holding.'});return}
    setBusy(true); let got=0; let messages=[];
    try{
      if(stockHoldings.length){
        const raw=await fetchStockLtp({baseUrl:market.stockBaseUrl,token:market.stockToken,instruments:stockHoldings.map(a=>a.marketToken),proxyUrl:market.proxyUrl});
        const mapped=normalizeStockQuoteMap(raw); setQuotes(q=>({...q,...mapped})); got+=Object.keys(mapped).length;
      }
      if(mfHoldings.length){
        const url=market.proxyUrl?`${market.proxyUrl.replace(/\/$/,'')}/api/market/mf-nav` : undefined;
        const navs=await fetchAmfiNavs(url); const next={};
        mfHoldings.forEach(a=>{const q=navs.get(a.amfiIsin);if(q)next[a.amfiIsin]=q.nav});
        setQuotes(q=>({...q,...next})); got+=Object.keys(next).length;
      }
      setLast(new Date()); setStatus({ok:got>0,message:`Updated ${got} holding${got===1?'':'s'}${market.proxyUrl?' · proxy enabled':''}.`});
    }catch(e){setStatus({ok:false,message:e.message||'Market update failed.'});}
    finally{setBusy(false)}
  };
  useEffect(()=>{refresh();const timer=setInterval(refresh,30000);return()=>clearInterval(timer)},[market.stockBaseUrl,market.stockToken,market.proxyUrl,stockHoldings.map(a=>a.marketToken).join(','),mfHoldings.map(a=>a.amfiIsin).join(',')]);
  useEffect(()=>{if(!market.proxyUrl||!stockHoldings.length)return;const ws=connectStockStream({proxyUrl:market.proxyUrl,instruments:stockHoldings.map(a=>a.marketToken),onTick:msg=>{const token=msg.instrument?stockHoldings.find(a=>String(a.marketToken).endsWith(`:${msg.instrument}`))?.marketToken:null;const ltp=Number(msg?.data?.ltp);if(token&&Number.isFinite(ltp))setQuotes(q=>({...q,[token]:ltp}));setLast(new Date())},onStatus:s=>setStatus(x=>({...x,ok:s.connected??x.ok,message:s.message||'Live stream connected.'}))});return()=>ws?.close()},[market.proxyUrl,stockHoldings.map(a=>a.marketToken).join(',')]);
  const liveRows=holdings.map(a=>{const key=a.marketToken;const live= a.type==='Equity' ? quotes[key] : a.type==='Mutual Fund' ? quotes[a.amfiIsin] : null; return live?calcHolding(a,live):a;}).filter(a=>a.value>0);
  const liveTotal=liveRows.reduce((s,a)=>s+Number(a.value||0),0); const cost=liveRows.reduce((s,a)=>s+Number(a.invested||0),0); const pnl=liveTotal-cost;
  return <>
    <Card className="marketPanel"><MarketStatus status={status} onRefresh={refresh}/><div className="marketSummary"><Stat label="Live portfolio value" value={money(liveTotal)} sub={last?`Updated ${last.toLocaleTimeString('en-IN')}`:'Waiting for update'} positive={pnl>=0}/><Stat label="Live P&L" value={money(pnl)} sub={cost?`${pct(pnl/cost*100)} on tracked cost`:'Add invested cost'} positive={pnl>=0}/><Stat label="Auto refresh" value="30 sec" sub={market.proxyUrl?'WebSocket + REST':'REST fallback'} /></div></Card>
    <div className="assetList marketRows">{liveRows.length?liveRows.map(a=>{const live=a.type==='Equity'?quotes[a.marketToken]:a.type==='Mutual Fund'?quotes[a.amfiIsin]:null;const pl=Number(a.value)-Number(a.invested||0);return <Card key={a.id}><div className="assetRow"><div><b>{a.name}</b><small>{a.type} · {live?`Live ${money(live)}`:'No live quote configured'}</small></div><div><strong>{money(a.value)}</strong><small className={pl>=0?'positive':'negative'}>{pl>=0?'+':''}{money(pl)} · {a.invested?pct(pl/a.invested*100):'—'}</small></div><div><span className={live?'liveBadge':'mutedBadge'}>{live?'LIVE':'OFFLINE'}</span></div></div></Card>}) : <Empty title="No live holdings" text="Add market identifiers to your equity or mutual-fund assets."/>}</div>
  </>
}
function HoldingsPage({data,setData}){
  const [selected,setSelected]=useState(null); const [q,setQ]=useState('');
  const list=data.assets.filter(a=>['Equity','Mutual Fund','Gold'].includes(a.type)).filter(a=>a.name.toLowerCase().includes(q.toLowerCase()));
  const txs=data.investmentTransactions||[]; const realized=txs.reduce((s,t)=>s+Number(t.realizedPnl||0),0);
  const portfolioCashflows=(asset)=>{
    const rows=(data.investmentTransactions||[]).filter(t=>t.assetId===asset.id).map(t=>{
      if(['BUY','SIP'].includes(t.type)) return {date:t.date,amount:-(Number(t.units||0)*Number(t.price||0)+Number(t.fees||0))};
      if(t.type==='SELL') return {date:t.date,amount:Number(t.units||0)*Number(t.price||0)-Number(t.fees||0)};
      if(t.type==='DIVIDEND') return {date:t.date,amount:Number(t.dividend||0)};
      if(t.type==='FEE') return {date:t.date,amount:-Number(t.fees||0)};
      return null;
    }).filter(Boolean);
    rows.push({date:today(),amount:Number(asset.value||0)}); return rows;
  };
  return <><PageTitle title="Investment Portfolio" text="Transaction-based portfolio tracking, FIFO cost lots and live market intelligence."><div className="quickActions"><Button onClick={()=>list[0]&&setSelected(list[0])}><Plus size={16}/> Add transaction</Button></div></PageTitle>
    <Card><div className="summaryStrip"><Stat label="Holdings" value={list.length}/><Stat label="Transactions" value={txs.length}/><Stat label="Realized P&L" value={money(realized)} positive={realized>=0}/><Stat label="Method" value="FIFO" sub="Cost lots"/></div><div className="search"><Search size={17}/><input placeholder="Search holdings..." value={q} onChange={e=>setQ(e.target.value)}/></div></Card>
    <MarketPortfolio data={data} setData={setData}/>
    <div className="assetList mt">{list.length?list.map(a=>{const pl=Number(a.value||0)-Number(a.invested||0);const xr=xirr(portfolioCashflows(a));return <Card key={a.id}><div className="assetRow"><div><b>{a.name}</b><small>{a.type}{a.units?` · ${Number(a.units).toFixed(4)} units`:''}</small></div><div><strong>{money(a.value)}</strong><small className={pl>=0?'positive':'negative'}>{pl>=0?'+':''}{money(pl)} · {xr==null?'—':pct(xr)} XIRR</small></div><div className="quickActions"><Button secondary onClick={()=>setSelected(a)}><Plus size={15}/> Transaction</Button></div></div></Card>)}):<Empty title="No holdings" text="Add an equity, mutual fund or gold asset first."/>}</div>
    {selected&&<InvestmentTransactions asset={selected} data={data} setData={setData} onClose={()=>setSelected(null)}/>}<Card className="mt"><div className="cardHead"><h2>Recent investment transactions</h2></div>{txs.slice(0,12).map(t=>{const a=data.assets.find(x=>x.id===t.assetId);return <div className="expenseRow" key={t.id}><div><b>{t.type} · {a?.name||'Unknown asset'}</b><small>{t.date} · {t.units?`${t.units} units`:''}</small></div><strong>{t.type==='DIVIDEND'?money(t.dividend):t.type==='FEE'?`−${money(t.fees)}`:t.type==='SELL'?`P&L ${money(t.realizedPnl||0)}`:`${money((t.units||0)*(t.price||0))}`}</strong></div>)}</Card>
  </>;
}
function Assets({data,setData}){const [open,setOpen]=useState(false);const [f,setF]=useState({name:'',type:'Savings',value:'',invested:'',units:'',price:'',marketToken:'',amfiIsin:''});const add=()=>{if(!f.name||!f.value)return;setData(d=>({...d,assets:[...d.assets,{...f,id:id(),value:+f.value,invested:+(f.invested||f.value),units:f.units?+f.units:null,price:f.price?+f.price:null,marketToken:f.marketToken.trim(),amfiIsin:f.amfiIsin.trim(),updatedAt:new Date().toISOString()}]}));setF({name:'',type:'Savings',value:'',invested:'',units:'',price:'',marketToken:'',amfiIsin:''});setOpen(false)};return <><PageTitle title="Assets" text="Track savings, cash, FD/RD, stocks, mutual funds, gold and other wealth."><Button onClick={()=>setOpen(true)}><Plus size={16}/> Add asset</Button></PageTitle><div className="assetList">{data.assets.map(a=><Card key={a.id}><div className="assetRow"><div><b>{a.name}</b><small>{a.type}{a.units?` · ${a.units} units`:''}</small></div><div><strong>{money(a.value)}</strong><small>{a.invested?`${pct((a.value-a.invested)/a.invested*100)} return`:''}</small></div><button className="iconBtn danger" onClick={()=>setData(d=>({...d,assets:d.assets.filter(x=>x.id!==a.id)}))}><Trash2 size={16}/></button></div></Card>)}</div>{open&&<Modal title="Add asset" onClose={()=>setOpen(false)}><div className="modalGrid"><Field label="Name"><input value={f.name} onChange={e=>setF({...f,name:e.target.value})}/></Field><Field label="Type"><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{assetTypes.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Current value"><input type="number" value={f.value} onChange={e=>setF({...f,value:e.target.value})}/></Field><Field label="Invested / cost"><input type="number" value={f.invested} onChange={e=>setF({...f,invested:e.target.value})}/></Field><Field label="Units (optional)"><input type="number" value={f.units} onChange={e=>setF({...f,units:e.target.value})}/></Field><Field label="Price/NAV (optional)"><input type="number" value={f.price} onChange={e=>setF({...f,price:e.target.value})}/></Field><Field label="Stock market token (optional)"><input placeholder="e.g. NSE:2885" value={f.marketToken} onChange={e=>setF({...f,marketToken:e.target.value})}/></Field><Field label="Mutual-fund ISIN (optional)"><input placeholder="e.g. INF247L01..." value={f.amfiIsin} onChange={e=>setF({...f,amfiIsin:e.target.value})}/></Field></div><div className="modalActions"><Button secondary onClick={()=>setOpen(false)}>Cancel</Button><Button onClick={add}>Save asset</Button></div></Modal>}</>}
function Transactions({type,data,setData}){const [kind,setKind]=useState(type);const [q,setQ]=useState('');const [f,setF]=useState({amount:'',category:'Food',note:'',date:today()});const month=today().slice(0,7);const items=data[kind==='expense'?'expenses':'income'];const cats=kind==='expense'?expenseCats:incomeCats;const add=()=>{if(!f.amount)return;const key=kind==='expense'?'expenses':'income';setData(d=>({...d,[key]:[{...f,id:id(),amount:+f.amount},...d[key]]}));setF({amount:'',category:cats[0],note:'',date:today()})};const filtered=items.filter(x=>(x.note||'').toLowerCase().includes(q.toLowerCase())||(x.category||'').toLowerCase().includes(q.toLowerCase()));const total=items.filter(x=>String(x.date).startsWith(month)).reduce((s,x)=>s+x.amount,0);return <><PageTitle title="Expenses & Income" text="Fast transaction entry with categories, search and recurring support."><div className="toggle"><button className={kind==='expense'?'sel':''} onClick={()=>setKind('expense')}>Expenses</button><button className={kind==='income'?'sel':''} onClick={()=>setKind('income')}>Income</button></div></PageTitle><Card><div className="formGrid"><input type="number" placeholder="Amount ₹" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{cats.map(x=><option key={x}>{x}</option>)}</select><input placeholder="Note" value={f.note} onChange={e=>setF({...f,note:e.target.value})}/><input type="date" value={f.date} onChange={e=>setF({...f,date:e.target.value})}/><Button onClick={add}><Plus size={16}/> Add</Button></div></Card><Card className="mt"><div className="summaryStrip"><Stat label={`This month ${kind}`} value={money(total)}/><Stat label="Transactions" value={items.length}/><Stat label="Recurring" value={data.recurring.length}/></div><div className="search"><Search size={17}/><input placeholder="Search category or note..." value={q} onChange={e=>setQ(e.target.value)}/></div>{filtered.length?filtered.map(x=><div className="expenseRow" key={x.id}><div><b>{x.category}</b><small>{x.note||'No note'} · {x.date}</small></div><strong className={kind==='expense'?'negative':'positive'}>{kind==='expense'?'−':'+'}{money(x.amount)}</strong><button className="iconBtn danger" onClick={()=>setData(d=>({...d,[kind==='expense'?'expenses':'income']:d[kind==='expense'?'expenses':'income'].filter(y=>y.id!==x.id)}))}><Trash2 size={16}/></button></div>):<Empty title="No transactions" text="Add your first transaction above."/>}</Card></>}
function Cards({data,setData}){const [f,setF]=useState({name:'',limit:'',outstanding:'',statement:'',due:'',minimum:'',rewards:''});const add=()=>{if(!f.name)return;setData(d=>({...d,cards:[...d.cards,{...f,id:id(),limit:+f.limit||0,outstanding:+f.outstanding||0,minimum:+f.minimum||0}]}));setF({name:'',limit:'',outstanding:'',statement:'',due:'',minimum:'',rewards:''})};return <><PageTitle title="Credit Cards" text="Track limits, utilization, bills, due dates and rewards."/><Card><div className="formGrid"><input placeholder="Card name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input type="number" placeholder="Credit limit" value={f.limit} onChange={e=>setF({...f,limit:e.target.value})}/><input type="number" placeholder="Outstanding" value={f.outstanding} onChange={e=>setF({...f,outstanding:e.target.value})}/><input type="date" title="Statement date" value={f.statement} onChange={e=>setF({...f,statement:e.target.value})}/><Button onClick={add}><Plus size={16}/> Add card</Button></div></Card><div className="assetList">{data.cards.length?data.cards.map(c=><Card key={c.id}><div className="cardDetail"><div><b>{c.name}</b><small>Utilization {pct(c.limit?c.outstanding/c.limit*100:0)}</small></div><div><strong>{money(c.outstanding)}</strong><small>of {money(c.limit)}</small></div><div><span>Due {c.due||'—'}</span><span>Minimum {money(c.minimum)}</span></div><button className="iconBtn danger" onClick={()=>setData(d=>({...d,cards:d.cards.filter(x=>x.id!==c.id)}))}><Trash2 size={16}/></button></div></Card>):<Card><Empty icon={<CreditCard/>} title="No cards added" text="Add a credit card to track utilization and due dates."/></Card>}</div></>}
function Debts({data,setData}){const [f,setF]=useState({name:'',principal:'',outstanding:'',rate:'',emi:'',tenure:'',due:''});const add=()=>{if(!f.name)return;setData(d=>({...d,debts:[...d.debts,{...f,id:id(),principal:+f.principal||0,outstanding:+f.outstanding||0,rate:+f.rate||0,emi:+f.emi||0,tenure:+f.tenure||0}]}));setF({name:'',principal:'',outstanding:'',rate:'',emi:'',tenure:'',due:''})};return <><PageTitle title="Debts / Loans" text="Track principal, interest, EMI, tenure and repayment progress."/><Card><div className="formGrid"><input placeholder="Loan / debt name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input type="number" placeholder="Principal" value={f.principal} onChange={e=>setF({...f,principal:e.target.value})}/><input type="number" placeholder="Outstanding" value={f.outstanding} onChange={e=>setF({...f,outstanding:e.target.value})}/><input type="number" placeholder="Interest %" value={f.rate} onChange={e=>setF({...f,rate:e.target.value})}/><Button onClick={add}><Plus size={16}/> Add debt</Button></div></Card><div className="assetList">{data.debts.length?data.debts.map(d=><Card key={d.id}><div className="debtDetail"><div><b>{d.name}</b><small>{d.rate}% interest · EMI {money(d.emi)}</small></div><strong>{money(d.outstanding)}</strong><div className="progress"><i style={{width:`${Math.min(100,d.principal?((d.principal-d.outstanding)/d.principal)*100:0)}%`}}/></div><button className="iconBtn danger" onClick={()=>setData(x=>({...x,debts:x.debts.filter(y=>y.id!==d.id)}))}><Trash2 size={16}/></button></div></Card>):<Card><Empty icon={<Landmark/>} title="Debt-free" text="Add a loan only if you need to track one."/></Card>}</div></>}
function Insurance({data,setData}){const [f,setF]=useState({name:'',type:'Health',coverage:'',premium:'',frequency:'Yearly',renewal:'',policy:'',nominee:''});const add=()=>{if(!f.name)return;setData(d=>({...d,insurance:[...d.insurance,{...f,id:id(),coverage:+f.coverage||0,premium:+f.premium||0}]}));setF({name:'',type:'Health',coverage:'',premium:'',frequency:'Yearly',renewal:'',policy:'',nominee:''})};return <><PageTitle title="Insurance" text="Keep policy details, coverage, premiums and renewals in one place."/><Card><div className="formGrid"><input placeholder="Policy name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><select value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{['Health','Life','Term','Vehicle','Other'].map(x=><option key={x}>{x}</option>)}</select><input type="number" placeholder="Coverage" value={f.coverage} onChange={e=>setF({...f,coverage:e.target.value})}/><input type="number" placeholder="Premium" value={f.premium} onChange={e=>setF({...f,premium:e.target.value})}/><Button onClick={add}><Plus size={16}/> Add policy</Button></div></Card><div className="assetList">{data.insurance.map(i=><Card key={i.id}><div className="cardDetail"><div><b>{i.name}</b><small>{i.type} · Renewal {i.renewal||'—'}</small></div><div><strong>{money(i.coverage)}</strong><small>Coverage</small></div><div><span>{money(i.premium)} / {i.frequency}</span><span>Policy {i.policy||'—'}</span></div><button className="iconBtn danger" onClick={()=>setData(d=>({...d,insurance:d.insurance.filter(x=>x.id!==i.id)}))}><Trash2 size={16}/></button></div></Card>)}{!data.insurance.length&&<Card><Empty icon={<ShieldCheck/>} title="No policies" text="Add your health, life, term or vehicle insurance."/></Card>}</div></>}
function Goals({data,setData}){const [f,setF]=useState({name:'',target:'',current:'',deadline:''});const add=()=>{if(!f.name||!f.target)return;setData(d=>({...d,goals:[...d.goals,{...f,id:id(),target:+f.target,current:+f.current||0}]}));setF({name:'',target:'',current:'',deadline:''})};return <><PageTitle title="Goals" text="Build targets and see progress toward the amount and deadline."><Button onClick={add}><Plus size={16}/> Add goal</Button></PageTitle><Card><div className="formGrid"><input placeholder="Goal name" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input type="number" placeholder="Target ₹" value={f.target} onChange={e=>setF({...f,target:e.target.value})}/><input type="number" placeholder="Current ₹" value={f.current} onChange={e=>setF({...f,current:e.target.value})}/><input type="date" value={f.deadline} onChange={e=>setF({...f,deadline:e.target.value})}/><Button onClick={add}><Plus size={16}/> Save</Button></div></Card><div className="goalGrid">{data.goals.map(g=>{const progress=Math.min(100,g.target?g.current/g.target*100:0);const months=g.deadline?Math.max(1,(new Date(g.deadline)-new Date())/(1000*60*60*24*30.4)):null;const required=months?Math.max(0,(g.target-g.current)/months):null;return <Card key={g.id}><div className="goal"><div className="goalTop"><div><b>{g.name}</b><small>{g.deadline?'Target '+g.deadline:'No deadline'}</small></div><button className="iconBtn danger" onClick={()=>setData(d=>({...d,goals:d.goals.filter(x=>x.id!==g.id)}))}><Trash2 size={16}/></button></div><div className="goalMoney"><strong>{money(g.current)}</strong><span>of {money(g.target)}</span></div><div className="progress"><i style={{width:progress+'%'}}/></div><div className="goalFoot"><span>{progress.toFixed(0)}% complete</span>{required!==null&&<span>~{money(required)}/month</span>}</div></div></Card>})}{!data.goals.length&&<Card><Empty icon={<Target/>} title="No goals yet" text="Create an emergency fund, travel, vehicle or any custom goal."/></Card>}</div></>}
function Reminders({data,setData}){const [f,setF]=useState({name:'',due:'',amount:'',category:'Bill'});const add=()=>{if(!f.name)return;setData(d=>({...d,reminders:[...d.reminders,{...f,id:id(),amount:+f.amount||0}]}));setF({name:'',due:'',amount:'',category:'Bill'})};return <><PageTitle title="Reminders" text="Payments, renewals, SIPs, bills and custom reminders."/><Card><div className="formGrid"><input placeholder="Reminder" value={f.name} onChange={e=>setF({...f,name:e.target.value})}/><input type="date" value={f.due} onChange={e=>setF({...f,due:e.target.value})}/><input type="number" placeholder="Amount ₹" value={f.amount} onChange={e=>setF({...f,amount:e.target.value})}/><input placeholder="Category" value={f.category} onChange={e=>setF({...f,category:e.target.value})}/><Button onClick={add}><Plus size={16}/> Add</Button></div></Card><div className="assetList">{data.reminders.map(r=><Card key={r.id}><div className="lineRow"><div><b>{r.name}</b><small>{r.category} · {r.due||'No date'}</small></div><strong>{money(r.amount)}</strong><button className="iconBtn danger" onClick={()=>setData(d=>({...d,reminders:d.reminders.filter(x=>x.id!==r.id)}))}><Trash2 size={16}/></button></div></Card>)}{!data.reminders.length&&<Card><Empty icon={<Bell/>} title="No reminders" text="Add a due date or financial reminder."/></Card>}</div></>}
function analytics(data){
 const assets=data.assets||[], income=data.income||[], expenses=data.expenses||[], debts=data.debts||[], cards=data.cards||[];
 const assetTotal=assets.reduce((s,a)=>s+Number(a.value||0),0), liabilities=debts.reduce((s,a)=>s+Number(a.outstanding||0),0)+cards.reduce((s,a)=>s+Number(a.outstanding||0),0), netWorth=assetTotal-liabilities;
 const invested=assets.filter(a=>['Equity','Mutual Fund','Gold','Crypto'].includes(a.type)).reduce((s,a)=>s+Number(a.value||0),0);
 const investedCost=assets.filter(a=>['Equity','Mutual Fund','Gold','Crypto'].includes(a.type)).reduce((s,a)=>s+Number(a.invested||a.value||0),0);
 const months={}; [...income.map(x=>({...x,_kind:'income'})),...expenses.map(x=>({...x,_kind:'expense'}))].forEach(x=>{const m=String(x.date||'').slice(0,7);if(!/^\d{4}-\d{2}$/.test(m))return;months[m] ||= {income:0,expense:0};months[m][x._kind]+=Number(x.amount||0)});
 const monthRows=Object.entries(months).sort(([a],[b])=>a.localeCompare(b)).slice(-6).map(([month,v])=>({...v,month,net:v.income-v.expense,savings:v.income?((v.income-v.expense)/v.income*100):0}));
 const categories={};expenses.forEach(e=>categories[e.category]=(categories[e.category]||0)+Number(e.amount||0));
 const allocation={};assets.forEach(a=>allocation[a.type]=(allocation[a.type]||0)+Number(a.value||0));
 const savingsIncome=monthRows.reduce((s,m)=>s+m.income,0), savingsExpense=monthRows.reduce((s,m)=>s+m.expense,0);
 const avgMonthlySavings=monthRows.length?(savingsIncome-savingsExpense)/monthRows.length:0;
 const goalForecast=(data.goals||[]).map(g=>{const remaining=Math.max(0,Number(g.target||0)-Number(g.current||0));const monthsLeft=g.deadline?Math.max(0,(new Date(g.deadline)-new Date())/(1000*60*60*24*30.44)):null;const needed=monthsLeft?remaining/monthsLeft:null;return {...g,remaining,monthsLeft,needed}});
 return {assetTotal,liabilities,netWorth,invested,investedCost,returnPct:investedCost?(invested-investedCost)/investedCost*100:0,monthRows,categories,allocation,savingsIncome,savingsExpense,avgMonthlySavings,goalForecast};
}
function MiniLineChart({points=[],label='Net worth'}){if(!points.length)return <div className="chartEmpty">Add assets, income or expenses to build history.</div>;const vals=points.map(p=>Number(p.value||0));const min=Math.min(...vals),max=Math.max(...vals),range=max-min||1;const w=640,h=190,pad=20;const d=points.map((p,i)=>`${i?'L':'M'} ${(i/(Math.max(1,points.length-1)))*(w-pad*2)+pad} ${h-pad-((Number(p.value)-min)/range)*(h-pad*2)}`).join(' ');return <div className="chartWrap"><svg viewBox={`0 0 ${w} ${h}`} role="img" aria-label={label}><path className="chartArea" d={`${d} L ${w-pad} ${h-pad} L ${pad} ${h-pad} Z`}/><path className="chartLine" d={d}/>{points.map((p,i)=>{const x=(i/(Math.max(1,points.length-1)))*(w-pad*2)+pad;const y=h-pad-((Number(p.value)-min)/range)*(h-pad*2);return <circle key={i} cx={x} cy={y} r="4"/>})}</svg><div className="chartLabels"><span>{points[0].label}</span><b>{money(vals[vals.length-1])}</b><span>{points[points.length-1].label}</span></div></div>}
function CashflowChart({rows}){if(!rows.length)return <div className="chartEmpty">Add dated income and expense entries to see monthly cash flow.</div>;const max=Math.max(1,...rows.map(r=>Math.max(r.income,r.expense)));return <div className="cashChart">{rows.map(r=><div className="cashCol" key={r.month}><div className="cashBars"><i style={{height:`${r.income/max*100}%`}}/><em style={{height:`${r.expense/max*100}%`}}/></div><small>{r.month.slice(5)}</small><b>{money(r.net)}</b></div>)}</div>}
function Insights({data}){const a=analytics(data);const snapshots=(data.snapshots||[]).slice().sort((x,y)=>String(x.date).localeCompare(String(y.date))).slice(-12);const trend=snapshots.map(s=>({label:String(s.date).slice(5),value:Number(s.netWorth||0)}));const allocEntries=Object.entries(a.allocation).sort((x,y)=>y[1]-x[1]);const totalAlloc=a.assetTotal||1;const topExpense=Object.entries(a.categories).sort((x,y)=>y[1]-x[1])[0];const emergency=data.assets.filter(x=>['Savings','Cash','FD','RD'].includes(x.type)).reduce((s,x)=>s+Number(x.value||0),0);const monthlyExpense=a.monthRows.length?a.monthRows.reduce((s,x)=>s+x.expense,0)/a.monthRows.length:0;const coverage=monthlyExpense?emergency/monthlyExpense:0;return <>
 <PageTitle title="Insights" text="Your financial health, trends and decision signals."/>
 <div className="statsGrid"><Stat label="Net worth" value={money(a.netWorth)} sub={`${money(a.assetTotal)} assets · ${money(a.liabilities)} liabilities`} positive={a.netWorth>=0}/><Stat label="Investment return" value={pct(a.returnPct)} sub="Tracked cost vs current value" positive={a.returnPct>=0}/><Stat label="Avg. monthly savings" value={money(a.avgMonthlySavings)} sub="Last 6 available months" positive={a.avgMonthlySavings>=0}/><Stat label="Savings rate" value={pct(a.savingsIncome?a.avgMonthlySavings/a.savingsIncome*100:0)} sub="Across available months" positive={a.avgMonthlySavings>=0}/><Stat label="Cash runway" value={`${coverage.toFixed(1)} mo`} sub="Liquid assets / avg expenses" positive={coverage>=6}/><Stat label="Top expense" value={topExpense?money(topExpense[1]):'—'} sub={topExpense?topExpense[0]:'No expense data'}/></div>
 <div className="grid2"><Card><Head n="01" title="Net-worth trend"/><MiniLineChart points={trend}/></Card><Card><Head n="02" title="Monthly cash flow"/><CashflowChart rows={a.monthRows}/></Card></div>
 <div className="grid2"><Card><Head n="03" title="Asset allocation"/><div className="allocationBars">{allocEntries.map(([k,v])=><div className="allocRow" key={k}><div><b>{k}</b><span>{money(v)} · {pct(v/totalAlloc*100)}</span></div><i><em style={{width:`${v/totalAlloc*100}%`}}/></i></div>)}{!allocEntries.length&&<Empty icon={<WalletCards/>} title="No assets yet" text="Add assets to see your allocation."/>}</div></Card><Card><Head n="04" title="Expense intelligence"/>{Object.entries(a.categories).sort((x,y)=>y[1]-x[1]).slice(0,6).map(([k,v])=><div className="barRow" key={k}><div><b>{k}</b><span>{money(v)}</span></div><i><em style={{width:`${a.savingsExpense?v/a.savingsExpense*100:0}%`}}/></i></div>)}{!Object.keys(a.categories).length&&<Empty icon={<Receipt/>} title="Not enough data" text="Add expenses to reveal spending patterns."/>}</Card></div>
 <Card className="mt"><Head n="05" title="Goal forecast"/>{a.goalForecast.length?a.goalForecast.map(g=><div className="goalInsight" key={g.id}><div><b>{g.name}</b><small>{money(g.remaining)} remaining {g.deadline?`· ${g.deadline}`:''}</small></div><strong>{g.needed!==null?`${money(g.needed)}/mo needed`:'Add a deadline'}</strong></div>):<Empty icon={<Target/>} title="No goals yet" text="Create goals to get monthly funding targets."/>}</Card>
 <Card className="mt"><Head n="06" title="Financial signals"/><div className="signalGrid"><div className={coverage>=6?'signal good':'signal warn'}><b>{coverage>=6?'Healthy cash runway':'Build your emergency buffer'}</b><span>{coverage?`${coverage.toFixed(1)} months of average expenses covered.`:'Add liquid assets and expenses to calculate runway.'}</span></div><div className={a.avgMonthlySavings>=0?'signal good':'signal bad'}><b>{a.avgMonthlySavings>=0?'Positive savings trend':'Spending exceeds income'}</b><span>{a.avgMonthlySavings>=0?`Average monthly surplus is ${money(a.avgMonthlySavings)}.`:`Average monthly deficit is ${money(Math.abs(a.avgMonthlySavings))}.`}</span></div><div className={a.assetTotal?(a.invested/a.assetTotal<=0.85?'signal good':'signal warn'):'signal warn'}><b>{a.assetTotal&&a.invested/a.assetTotal>0.85?'High investment concentration':'Diversification check'}</b><span>{a.assetTotal?`${pct(a.invested/a.assetTotal*100)} of assets are in tracked growth assets.`:'Add assets to assess concentration.'}</span></div></div></Card>
 </>}
function MarketSettings({data,setData}){const m=data.settings.market||{};const [f,setF]=useState({stockBaseUrl:m.stockBaseUrl||'https://api.indstocks.com',stockToken:m.stockToken||'',proxyUrl:m.proxyUrl||''});const save=()=>setData(d=>({...d,settings:{...d.settings,market:{...d.settings.market,...f}}}));return <Card className="marketConfig"><div className="cardHead"><h2><span>LIVE</span>Market data connection</h2></div><div className="setting"><TrendingUp/><div><b>INDstocks stock quotes</b><span>API access is currently free; access tokens expire after 24 hours. Read-only quote endpoints do not require a static IP.</span></div></div><div className="marketFields"><Field label="Stock API base URL"><input value={f.stockBaseUrl} onChange={e=>setF({...f,stockBaseUrl:e.target.value})}/></Field><Field label="Access token (leave blank if using proxy)"><input type="password" value={f.stockToken} onChange={e=>setF({...f,stockToken:e.target.value})}/></Field><Field label="Market proxy URL (recommended)"><input placeholder="https://your-domain.example" value={f.proxyUrl} onChange={e=>setF({...f,proxyUrl:e.target.value})}/></Field></div><div className="modalActions"><Button onClick={save}>Save market connection</Button></div><div className="marketNote">Your token is stored only in this app's local storage for this personal build. For a public production deployment, we should move secrets behind a small server-side proxy.</div></Card>}

function InstallCard(){const [deferred,setDeferred]=useState(null);const [installed,setInstalled]=useState(false);useEffect(()=>{const h=e=>{e.preventDefault();setDeferred(e)};window.addEventListener('beforeinstallprompt',h);setInstalled(window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true);return()=>window.removeEventListener('beforeinstallprompt',h)},[]);const install=async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;setDeferred(null)};return <Card><div className="setting"><Download/><div><b>Install My Wealth</b><span>{installed?'App is already installed or running standalone.':'Install it on your phone for an app-like, offline-first experience.'}</span></div>{!installed&&deferred&&<Button onClick={install}>Install</Button>}</div></Card>}
function SettingsPage({data,setData}){const exportData=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download='my-wealth-backup.json';a.click()};const importData=e=>{const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{setData({...base,...JSON.parse(r.result)});alert('Backup restored.')}catch{alert('Invalid backup file.')}};r.readAsText(file)};const reset=()=>{if(confirm('Delete all local app data?')){localStorage.removeItem('my-wealth-data');location.reload()}};return <><PageTitle title="Settings" text="Privacy-first controls, backups and app preferences."/><InstallCard/><Card><div className="setting"><Moon/><div><b>Appearance</b><span>Switch between light and dark mode from the sidebar.</span></div></div><div className="setting"><CircleDollarSign/><div><b>Currency</b><span>Indian Rupee (₹) is the default.</span></div></div><div className="setting"><Download/><div><b>Backup data</b><span>Export every locally stored record as JSON.</span></div><Button secondary onClick={exportData}>Export</Button></div><div className="setting"><Upload/><div><b>Restore backup</b><span>Import a previously exported JSON file.</span></div><label className="secondary fileBtn">Import<input type="file" accept="application/json" onChange={importData}/></label></div><MarketSettings data={data} setData={setData}/><div className="setting"><RefreshCw/><div><b>Market data architecture</b><span>Stocks use the INDstocks adapter when configured. Mutual-fund NAV uses AMFI's latest published feed. Gold will use a swappable provider adapter.</span></div></div><div className="setting"><Trash2/><div><b>Reset all local data</b><span>This cannot be undone.</span></div><Button danger onClick={reset}>Reset</Button></div></Card></>}
function MarketStatus({status,onRefresh}){return <div className="marketStatus"><span className={status?.ok?'liveDot':''}/><div><b>{status?.ok?'Market data connected':'Market data not connected'}</b><small>{status?.message||'Configure a provider in Settings to enable live prices.'}</small></div><button className="secondary" onClick={onRefresh}>Refresh</button></div>}

function App(){const[data,setData,ready]=useStore();const[page,setPage]=useState('Dashboard');const[dark,setDark]=useState(data.settings.theme==='dark');useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light';if(ready)setData(d=>({...d,settings:{...d.settings,theme:dark?'dark':'light'}}))},[dark,ready]);useEffect(()=>{'serviceWorker'in navigator&&navigator.serviceWorker.register('/sw.js').catch(()=>{})},[]);useEffect(()=>{if(!ready)return;const date=today();const assets=(data.assets||[]).reduce((s,a)=>s+Number(a.value||0),0);const debts=(data.debts||[]).reduce((s,a)=>s+Number(a.outstanding||0),0);const cards=(data.cards||[]).reduce((s,a)=>s+Number(a.outstanding||0),0);const netWorth=assets-debts-cards;setData(d=>{const snaps=d.snapshots||[];const existing=snaps.findIndex(x=>x.date===date);const point={id:existing>=0?snaps[existing].id:id(),date,netWorth,assets,liabilities:debts+cards};if(existing>=0&&Math.abs(Number(snaps[existing].netWorth||0)-netWorth)<0.01)return d;const next=[...snaps];if(existing>=0)next[existing]=point;else next.push(point);return {...d,snapshots:next.slice(-365)}})},[data.assets,data.debts,data.cards]);if(!ready)return <div className="bootScreen"><div className="brand">My <span>Wealth</span></div><p>Loading your private wealth database…</p></div>;return <Layout page={page} setPage={setPage} data={data} setData={setData} dark={dark} setDark={setDark}/>}
createRoot(document.getElementById('root')).render(<App/>);
